name: Run Tests on Code Change

on:
  push:
    branches: [main]
    paths:
      - '*/**'        # 仅当 src 目录下的代码变更时触发

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run if the file changed
        run: |
         echo "检测到文件变更，触发工作流！"
