name: Run Tests on Code Change

on:
  push:
    branches: [main]
    #paths:
      # - '*/**'        # 仓库中任何文件发生改变时都会触发工作流
jobs:
  lzx:
    runs-on: ubuntu-latest
    steps:
      - name: run if the file changed
        run: |
         echo "检测到文件变更，触发工作流！"
